import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/layouts/Header";
import { getCurrentSession } from "./actions/auth";
import { SanityLive } from "@/sanity/lib/live";
import CategorySelector from "./components/layouts/CategorySelector";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const { user } = await getCurrentSession();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-[200vh] `}
      >
        <Header user={user} categorySelector={<CategorySelector />} />
        {children}
        <SanityLive />
      </body>
    </html>
  );
};

export default RootLayout;
